apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-shop-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-shop-api
  template:
    metadata:
      labels:
        app: azure-shop-api
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: api
          image: acrazureshopk8s2833.azurecr.io/azure-shop-api:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: azure-shop-api
spec:
  selector:
    app: azure-shop-api
  ports:
    - port: 80
      targetPort: 8080
