apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-shop-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-shop-web
  template:
    metadata:
      labels:
        app: azure-shop-web
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: web
          image: acrazureshopk8s2833.azurecr.io/azure-shop-web:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: azure-shop-web
spec:
  type: LoadBalancer
  selector:
    app: azure-shop-web
  ports:
    - port: 80
      targetPort: 8080
